function [ MedF ] = FuncTs( IQ_Ts_Unshifted, Nfft, LevelOfIncreasing, ...
                                    Index_Pilot)
    [ AbsAutoCorr, AutoCorr, PositionTs1 ] = FuncCorrelation(...
        IQ_Ts_Unshifted, Nfft, LevelOfIncreasing );
    Fi =[];
    for k = 1 : length(IQ_Ts_Unshifted)/(Nfft + Nfft/8)
        MedF(k, :) = fft(...
                IQ_Ts_Unshifted(...
                    (k - 1)*(Nfft + Nfft/8) + PositionTs1 :...
                    (k - 1)*(Nfft + Nfft/8) + Nfft + PositionTs1 - 1));
        Fi = (angle(MedF(k,Index_Pilot(1))) -...
                angle(MedF(k,Index_Pilot(2)))) *...
            (Index_Pilot(1) : Index_Pilot(2))/...
            (Index_Pilot(1) - Index_Pilot(2)) + ...
            Index_Pilot(2)*angle(MedF(k,Index_Pilot(1))) - ...
            Index_Pilot(1)*angle(MedF(k,Index_Pilot(2)));
        for l = 2 : length(Index_Pilot) - 1
            % y = (y2 - y1)* x /(x2 - x1) + x2y1 - x1y2
            Fi = [ Fi Fi(Index_Pilot(l) - 1) + (angle(MedF(k,Index_Pilot(l))) -...
                    angle(MedF(k,Index_Pilot(l + 1)))) *...
                 (Index_Pilot(l) : Index_Pilot(l + 1))/...
                 (Index_Pilot(l) - Index_Pilot(l + 1)) + ...
                 Index_Pilot(l + 1)*angle(MedF(k,Index_Pilot(l))) - ...
                 Index_Pilot(l)*angle(MedF(k,Index_Pilot(l + 1)))];
        end
        Fi = [Fi zeros(1, Nfft - length(Fi))];
        MedF(k,:) = MedF(k,:).*exp(-1i*Fi);
    end
end

