function [ MedFi ] = FuncTs( IQ_Ts_Unshifted, Nfft, LevelOfIncreasing, ...
                                    Index_Pilot)
    [ AbsAutoCorr, AutoCorr, PositionTs1 ] = FuncCorrelation(...
        IQ_Ts_Unshifted, Nfft, LevelOfIncreasing );
    for k = 1 : length(IQ_Ts_Unshifted)/(Nfft + Nfft/8)
        MedF(k) = fft(...
                IQ_Ts_Unshifted(...
                    (k - 1)*(Nfft + Nfft/8) + PositionTs1 :...
                    (k - 1)*(Nfft + Nfft/8) + Nfft + PositionTs1 - 1));
        MedFi = abs(angle(MedF(Index_Pilot)) - pi);
        for l = 1 : length(Index_Pilot) - 1
            Fi(:) = angle(MedF(Index_Pilot(l)))*Index_Pilot(l + 1) -...
                 angle(MedF(Index_Pilot(l + 1)))*1 +...
                 (angle(MedF(Index_Pilot(l + 1)))...
                    - angle(MedF(Index_Pilot(l)))) * ...
                 (Index_Pilot(l) : Index_Pilot(l + 1));
            MedF(k) = MedF(k) * exp(-1i * Fi)
        end
    end
end

