%функция создания созвездия и однозначного сопоставления группы бит паре
%реальных и мнимых значений
function [ MedSignalInF ] = Mapper( Bits, Nsk )
%формируем массив из координат в созвездии и сопоставляем этой паре чисел
%кординаты в мнимой плоскости
% Nsk = 16;
% Bits = randi([0,1],1,(10*sqrt(Nsk)));
n=1;
    for k = 1  : sqrt(Nsk)
        for l = 1  : sqrt(Nsk)
            Dictionary1Re(n) = (2*k-1-sqrt(Nsk));
            Dictionary1Im(n) = (2*l-1-sqrt(Nsk));
            n = n + 1;
        end
    end
    Dictionary2 = [1 1 0 0;...
                  1 1 0 1;...
                  1 0 0 1;...
                  1 0 0 0;...
                  1 1 1 0;...
                  1 1 1 1;...
                  1 0 1 1;...
                  1 0 1 0;...
                  0 1 1 0;...
                  0 1 1 1;...
                  0 0 1 1;...
                  0 0 1 0;...
                  0 1 0 0;...
                  0 1 0 1;...
                  0 0 0 1;...
                  0 0 0 0];
    Dictionary2 = Dictionary2';
    Dictionary = [Dictionary1Re; Dictionary1Im ; Dictionary2];
    for k = 1 : sqrt(Nsk) : length(Bits)
        for l = 1 : Nsk 
            if ((Bits(k:k+sqrt(Nsk)-1))' == Dictionary(3:6,l))
                MedSignalInF(fix (k/sqrt(Nsk)) + 1) =...
                    complex(Dictionary(1,l),Dictionary(2,l));
                break;
            end
        end
    end
end
